# Generated by Django 4.2.7 on 2023-12-24 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_remove_car_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
